name: "WATCH ME FLY, [MAMA]!"

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install pydub
        sudo apt-get install ffmpeg
    - name: Less go
      run: python main.py
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: shuf
        path: shuffled_*
